# Site settings
title: Ser Confeiteira
email: contato@serconfeiteira.com.br
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.serconfeiteira.com.br" # the base hostname & protocol for your site
twitter_username: serconfeiteira

# Permalink configuration
permalink: /:categories/:title

# Pages links
links:
  - title: inicio
    url: /
  - title: sobre
    url: /sobre
  - title: contato
    url: /contato

# Build settings
markdown: kramdown
