# Site settings
title: Ser Confeiteira
email: contato@serconfeiteira.com.br
description: > # this means to ignore newlines until "baseurl:"
  Um blog sobre o dia-a-dia de se trabalhar com confeitaria. Os aprendizados e
  descobrimentos desse mundo de delícias.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://serconfeiteira.com.br" # the base hostname & protocol for your site

twitter: serconfeiteira
instagram: serconfeiteira

# Permalink configuration
permalink: "/blog/:title/"

# Pages links
links:
  - title: inicio
    url: /
  - title: sobre
    url: /sobre
  - title: contato
    url: /contato

# Open graph variables
fb_admins: https://www.facebook.com/samara.saheli
fb_appid: 237812806611517

# Gems
gems:
  - jekyll-paginate
  - jekyll-seo-tag

# Pagination
paginate: 4
paginate_path: "/blog/pag:num/"

# Build settings
markdown: kramdown
